### PR TITLE
new method to get platform scaling configuration

### PR DESCRIPTION
**Pull request by muhammad-amir-confiz**

### CODE REVIEW

**Comment by ibodrov** [comment]
@muhammad-amir-confiz could you please clean up the commit? There are some formatting changes in unrelated code.

**Comment by muhammad-amir-confiz** [comment]
@ibodrov 
done

**Comment by ibodrov** [comment]
@lkhusid could you please take a look and merge if it's ok?

**Comment by lkhusid** [comment]
This looks fine.   FYI,  you do not have to use  _.../platform/<PLATFORM>/edit_ url if you are just after platform CI  to check on its *availability* attribute value.   You can use _.../platform/<PLATFORM>_ url which will also give you platform CI.   The difference between these two end-points are in additional info included in response payload:  "edit" end-point will also include platform scaling relations and the other one will have dependencies (_LinksTo_ relations) to other platforms and cloud (_Consumes_ relations) info.

**Pull request merged**
